name: Publish documentation

on:
  push:
    paths:
    - "docs/**/*"
    - "mkdocs.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Add Python to the environment
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install python modules
      run: python -m pip install mkdocs mkdocs-material pymdown-extensions mkdocs-pdf-export-plugin
    - name: Build documentation
      run: python -m mkdocs build

    - name: Deploy the documentation
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
